/**
 * GenMedia Hub — Firebase Configuration & Initialization
 * AUTO-GENERATED by full-deploy.sh — do not edit manually
 */
import { initializeApp } from 'firebase/app';
import {
  getAuth,
  GoogleAuthProvider,
  signInWithPopup,
  signInWithRedirect,
  getRedirectResult,
  onAuthStateChanged,
  signOut,
} from 'firebase/auth';
import {
  getFirestore,
  collection,
  doc,
  setDoc,
  serverTimestamp,
} from 'firebase/firestore';

const firebaseConfig = {
  apiKey: 'AIzaSyChr3m4mnVkYwVm5ZnC8BhEAqWO74rR5W4',
  authDomain: 'casey-genmedia.firebaseapp.com',
  projectId: 'casey-genmedia',
  storageBucket: 'casey-genmedia.firebasestorage.app',
  messagingSenderId: '128509221012',
  appId: '1:128509221012:web:5bd73a95aea4b7a2837c81',
  measurementId: 'G-XXXXXXXXXX',
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

const googleProvider = new GoogleAuthProvider();
googleProvider.addScope('email');
googleProvider.addScope('profile');
googleProvider.setCustomParameters({ prompt: 'select_account' });

export async function signInWithGoogle() {
  try {
    const result = await signInWithPopup(auth, googleProvider);
    await ensureUserDocument(result.user);
    return result.user;
  } catch (error) {
    if (error.code === 'auth/popup-blocked') {
      await signInWithRedirect(auth, googleProvider);
      return null;
    }
    throw error;
  }
}

export async function handleRedirectResult() {
  const result = await getRedirectResult(auth);
  if (result?.user) await ensureUserDocument(result.user);
  return result?.user || null;
}

export async function logout() { await signOut(auth); }

export function onAuthChange(callback) {
  return onAuthStateChanged(auth, callback);
}

export async function getIdToken() {
  const user = auth.currentUser;
  if (!user) return null;
  return user.getIdToken();
}

async function ensureUserDocument(user) {
  const userRef = doc(db, 'users', user.uid);
  await setDoc(userRef, {
    email: user.email,
    displayName: user.displayName || 'Anonymous',
    photoURL: user.photoURL || null,
    lastLogin: serverTimestamp(),
    ...(user.metadata.creationTime === user.metadata.lastSignInTime
      ? { createdAt: serverTimestamp() } : {}),
  }, { merge: true });
}

export async function callMcpTool(server, tool, params = {}) {
  const token = await getIdToken();
  if (!token) throw new Error('Not authenticated. Please sign in first.');
  const response = await fetch('/api/mcpProxy', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify({ server, tool, params }),
  });
  if (!response.ok) {
    const error = await response.json().catch(() => ({ error: 'Unknown error' }));
    throw new Error(error.error || `MCP proxy error: ${response.status}`);
  }
  return response.json();
}

export { app, auth, db, googleProvider };
export default app;
